# Generated by Django 6.0.2 on 2026-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.ImageField(default='do', upload_to='fruits/'),
            preserve_default=False,
        ),
    ]
